export function handleException(err: Error) {
    console.error(err);

    alert("Aconteceu um erro inesperado.");
}
